# params: 62,051,613

base_model:
  _target_: models.transducer.Transducer

trainer:
  devices: [0]
  run_eagerly: false
  batch_size: 4
  epochs: 100
  workers: 4
  max_queue_size: 10
  use_multiprocessing: false
  log_interval: 500
  # model_path: outputs/tensorflow/checkpoints/rnnt_01_char.h5
  checkpoint:
    filepath: outputs/tensorflow/checkpoints/rnnt_{epoch:02d}_char.h5
    save_best_only: true
    save_weights_only: false
    save_freq: 2000
    monitor: loss
  tensorboard:
    log_dir: outputs/tensorflow/logs/rnnt/
    histogram_freq: 1
    write_graph: true
    write_images: true
    update_freq: 50
    profile_batch: 0

spec_augment:
  freq_masks: 2
  time_masks: 2
  freq_width: 15
  time_width: 25

train_ds:
  stage: train
  data_paths:
    - /workspace/datasets/tensorflow_asr_360.tsv
  shuffle: true
  cache: false
  buffer_size: 100
  drop_remainder: false
  num_print_sample_data: 1

validation_ds:
  stage: val
  data_paths:
    - /workspace/datasets/tensorflow_asr_val.tsv
  shuffle: false
  cache: true
  buffer_size: 100
  drop_remainder: false

audio_feature:
  sample_rate: 16000
  window_size: 0.02
  window_stride: 0.01
  n_mels: &n_mels 80
  preemph: 0.97
  dither: 1e-5
  pad_to: 16

text_feature:
  _target_: frontends.text_featurizer.CharFeaturizer
  vocabulary: null
  blank_at_zero: true

optimizer:
  name: adam
  learning_rate: 0.0005
  beta_1: 0.9
  beta_2: 0.999
 
  lr_scheduler:
    _target_: optimizers.lr_scheduler.WarmupCosineAnnealing
    warmup_ratio: 40000
    warmup_learning_rate: 1e-6
    hold_base_ratio: 0.6

  variational_noise:
    mean: 0
    stddev: 0.01
    start_step: 40000

encoder:
  _target_: modules.rnnt_encoder.RNNTEncoder
  dim_model: 320  # 640 in paper
  num_units: 1024 # 2048 in paper
  num_layers: 8 # 8 in paper
  reduction_indices: [0, 2] # [0, 2] in paper
  reduction_factors: [3, 2] # [3, 2] in paper

predictor:
  _target_: modules.transducer_predictor.TransducerPredictor
  num_layers: 2 # 2 in paper
  embed_dim: 320 # 640 in paper
  dim_model: 1024 # 2048 in paper
  dropout: 0.1
  random_state_sampling: true

joint:
  _target_: modules.transducer_joint.TransducerJoint
  dim_model: 320 # 640 in paper
  activation: tanh

tflite:
  model_path_from: outputs/tensorflow/checkpoints/rnnt_01_char_01.h5
  model_path_to: tflites/rnnt_char.tflite
  frame_length: 1.6 