base_model:
  _target_: models.ctc.CTC

trainer:
  devices: [0]
  run_eagerly: false
  batch_size: 4
  epochs: 100
  workers: 4
  max_queue_size: 10
  use_multiprocessing: false
  log_interval: 300
  checkpoint:
    filepath: outputs/tensorflow/checkpoints/jasper_{epoch:02d}_char.h5
    save_best_only: true
    save_weights_only: false
    save_freq: 2000
    monitor: loss
  tensorboard:
    log_dir: outputs/tensorflow/logs/jasper/
    histogram_freq: 1
    write_graph: true
    write_images: true
    update_freq: 50
    profile_batch: 0
  debugging: false

spec_augment:
  freq_masks: 2
  time_masks: 2
  freq_width: 15
  time_width: 25

train_ds:
  stage: train
  data_paths:
    - /workspace/datasets/tensorflow_asr_360.tsv
  shuffle: true
  cache: false
  buffer_size: 100
  drop_remainder: false
  num_print_sample_data: 1

validation_ds:
  stage: val
  data_paths:
    - /workspace/datasets/tensorflow_asr_val.tsv
  shuffle: false
  cache: true
  buffer_size: 100
  drop_remainder: false

audio_feature:
  sample_rate: 16000
  window_size: 0.02
  window_stride: 0.01
  n_mels: &n_mels 80
  preemph: 0.97
  dither: 1e-5
  pad_to: 16

text_feature:
  _target_: frontends.text_featurizer.CharFeaturizer
  vocab_path: null
  blank_at_zero: true
  normalize: true

optimizer:
  name: adam
  learning_rate: 0.001
  beta_1: 0.9
  beta_2: 0.999

encoder:
  _target_: modules.jasper_encoder.JasperEncoder
  num_sub_blocks: 2