encoder:
  _target_: rnnt_encoder.RNNTEncoder

  name: rnnt_encoder

  dim_model: 320
  num_units: 1024
  num_layers: 8
  reduction_indices: [0, 1]
  reduction_factors: [3, 2]

predictor:
  _target_: transducer_predictor.TransducerPredictor

  num_layers: 2
  embed_dim: 320
  dim_model: 1024
  
  random_state_sampling: true

joint:
  _target_: transducer_joint.TransducerJoint

  dim_model: 320
  activation: tanh

speech_config:
  sample_rate: 16000
  # frame_ms: 25
  # stride_ms: 10
  # num_feature_bins: 80
  # feature_type: log_mel_spectrogram
  # preemphasis: 0.97
  # normalize_signal: true
  # normalize_feature: true
  # normalize_per_feature: false

decoder_config:
  vocabulary: null
  target_vocab_size: 1024 # 16,384
  max_subword_length: 4 # 40
  blank_at_zero: true
  beam_width: 5
  norm_score: true

learning_config:
  train_dataset_config:
    stage: train
    use_tf: true
    data_paths:
      - /workspace/datasets/tensorflow_asr.tsv
    shuffle: true
    cache: true
    buffer_size: 100
    drop_remainder: true

  eval_dataset_config:
    stage: val
    use_tf: true
    data_paths:
      - /workspace/datasets/tensorflow_asr_val.tsv
    shuffle: false
    cache: true
    buffer_size: 100
    drop_remainder: true

  optimizer_config:
    class_name: adam
    config:
      learning_rate: 0.0001

  running_config:
    batch_size: 4
    num_epochs: 20
    checkpoint:
      filepath: outputs/tensorflow_asr/checkpoints/{epoch:02d}.h5
      save_best_only: true
      save_weights_only: false
      save_freq: epoch
    states_dir: outputs/tensorflow_asr/states
    tensorboard:
      log_dir: outputs/tensorflow_asr
      histogram_freq: 1
      write_graph: true
      write_images: true
      update_freq: epoch
      profile_batch: 2

tfrecords: false # Whether to use tfrecords
devices: [0] # Devices' ids to apply distributed training
mxp: true # Enable mixed precision
subwords: /workspace/datasets/subwords.subwords # Path to file that stores generated subwords
subwords_corpus: # Transcript files for generating subwords
  - /workspace/datasets/tensorflow_asr.tsv