encoder:
  _target_: emformer_encoder.EmformerEncoder

  feat_in: *n_mels
  num_layers: 16 # 26 for medium latency, 18 for low latency in paper
  num_heads: 8
  dim_model: 512
  dim_ffn: 2048
  dropout_attn: 0.1

  subsampling: vgg # frame stacking in paper
  subsampling_factor: 4
  subsampling_dim: 256 

  left_length: 20 # 800ms / (4 stacked frames x 10ms per frame)
  chunk_length: 32 # 1280ms / (4 stacked frames x 10ms per frame)
  right_length: 8 # 320ms / (4 stacked frames x 10ms per frame)

predictor:
  _target_: modules.transducer_predictor.TransducerPredictor

  num_layers: 1 # 2 in paper
  embed_dim: 320 # 256 in paper
  dim_model: 320 # 512 in paper

  random_state_sampling: true

joint:
  _target_: modules.transducer_joint.TransducerJoint
  
  dim_model: 320 # 640 in paper
  activation: tanh