trainer:
  gpus: -1
  max_epochs: 100
  num_nodes: 1
  accumulate_grad_batches: 1
  log_every_n_steps: 10
  amp_level: O1 # O1/O2 for mixed precision (O1 is recommended)
  precision: 16 # Should be set to 16 for O1 and O2 to enable the AMP.
  gradient_clip_val: 1
  weights_summary: full
  resume_from_checkpoint: null
  distributed_backend: ddp
  progress_bar_refresh_rate: 20 # for google colab
  default_root_dir: ./drive/MyDrive/jynote/emformer # for google colab

model:
  labels:
    [
      " ",
      "a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "k",
      "l",
      "m",
      "n",
      "o",
      "p",
      "q",
      "r",
      "s",
      "t",
      "u",
      "v",
      "w",
      "x",
      "y",
      "z",
      "'",
    ]

  train_ds:
    manifest_filepath: ./drive/MyDrive/jynote/manifest_train.json # for google colab
    sample_rate: 16000
    batch_size: 4
    max_duration: null
    min_duration: null
    shuffle: true
    num_workers: 4
    pin_memory: true
    normalize_transcripts: true # text to lowercase
    augmentor:
      speed:
        prob: 1.0
        sr: 16000
        resample_type: kaiser_fast

  validation_ds:
    manifest_filepath: ./drive/MyDrive/jynote/manifest_val.json # for google colab
    sample_rate: 16000
    batch_size: 4
    shuffle: false
    num_workers: 4
    pin_memory: false
    normalize_transcripts: true

  preprocessor:
    _target_: frontends.audio_preprocess.AudioToMelSpectrogramPreprocessor
    sample_rate: 16000
    window_size: 0.02
    window_stride: 0.01
    n_mels: &n_mels 80
    preemph: 0.97
    dither: 1e-5
    pad_to: 16
    stft_exact_pad: true
    stft_conv: true

  spec_augment:
    _target_: frontends.spec_augment.SpectrogramAugmentation
    freq_masks: 2
    time_masks: 2
    freq_width: 15
    time_width: 25
    rect_masks: 5
    rect_time: 25
    rect_freq: 15

  encoder:
    _target_: modules.emformer_encoder.EmformerEncoder
    subsampling: vgg # frame stacking is paper
    subsampling_factor: 4
    subsampling_dim: 256 # conv channels. used for vgg susampling

    feat_in: *n_mels

    num_layers: 16 # 26 for medium latency, 18 for low latency in paper
    num_heads: 8
    dim_model: 512
    dim_ffn: 2048
    dropout_attn: 0.1

    left_length: 20 # 800ms / (4 stacked frames x 10ms per frame)
    chunk_length: 32 # 1280ms / (4 stacked frames x 10ms per frame)
    right_length: 8 # 320ms / (4 stacked frames x 10ms per frame)

  predictor:
    _target_: modules.transducer_predictor.TransducerPredictor
    num_layers: 1 # 2 in paper
    embed_dim: 320 # 256 in paper
    dim_model: 320 # 512 in paper
    random_state_sampling: true

  joint:
    _target_: modules.transducer_joint.TransducerJoint
    dim_model: 320 # 640 in paper
    activation: tanh

  optimizer:
    name: adam

    lr: 0.0005

    betas: [0.9, 0.999]
    weight_decay: 0.0001

    variational_noise:
      mean: 0
      std: 0.075
      start_step: -1

    lr_scheduler:
      _target_: optimizers.lr_scheduler.CosineAnnealing
      warmup_ratio: 0.05
      min_lr: 1e-6
